version: '3.8'

services:
  frontend:
    container_name: con_frontend
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/code
      - /home/node/code/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true

# docker-compose up -d --build
#    depends_on:
#      - backend
